name: 🐛 Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
assignees: ["datawookie"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
        Please make sure there aren't any related (open or closed) issues already.
        
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Give a brief description of what happened and what should have happened.
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information which will help identifying, reproducing and fixing the problem.
      placeholder: |
              - Operating System
              - Software Versions
              - Repository Version
