name: ✨ Feature Request
description: Request a new feature or enhancement
labels: ["enhancement"]
title: "[FEAT]: "
body:
  - type: markdown
    attributes:
      value: |
        Please make sure there aren't any related (open or closed) issues already.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the feature or enhancement.
    validations:
      required: true
